### ISSUE TITLE
DPL-280 - ONT - Create a library or a pool

### ISSUE THREAD

**Issue by stevieing** [sanger/traction-ui#707]
**User story**
A laboratory user will either need to create a library (single sample - tagged or untagged) or a pool (multiplexed samples)

**Who are the primary contacts for this story**
Alex / Emma

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] Ability to select plates or tubes for the pool
- [ ] Ability to select tag set for the pool
- [ ] Ability to select individual samples from selected labware for pool
- [ ] Ability to autotag samples
- [ ] Ability to add fragment size (insert size), concentration, volumne, kit number and ligase batch number, state to each sample in pool
- [ ] Where possible reuse components for PacBio

References
This story has a relationship with sanger/traction-service#712

**Additional context**

**Comment by stevieing** [comment]
Paginator class for JSON API resource https://jsonapi-resources.com/v0.9/guide/resources.html#Pagination

**Comment by SujitDey2022** [comment]
This work will include  sanger/traction-ui#933

**Comment by stevieing** [comment]
I noticed a bug today. Not sure if this is newly introduced.
![Screenshot 2022-12-20 at 16 15 05](https://user-images.githubusercontent.com/519327/208714810-9546777a-f3f5-4d91-8660-9e51246f8b47.png)

```
A Module::DelegationError occurred in background at 2022-12-20 16:12:45 UTC :

 V1::Pacbio::ContainerMaterialResource#state delegated to material.state, but material is nil: #<V1::Pacbio::ContainerMaterialResource:0x00007fca495e3da8 @model=#<ContainerMaterial id: 18189, container_type: "Well", container_id: 9345, material_type: "Pacbio::Request", material_id: 3110, created_at: "2022-12-14 11:03:56.269593000 +0000", updated_at: "2022-12-14 11:03:56.269593000 +0000">, @context={}, @reload_needed=false, @changing=false, @save_needed=false>
 /var/www/traction-service/releases/20221220144339/app/resources/v1/pacbio/container_material_resource.rb:52:in `rescue in state'

-------------------------------
Backtrace:
-------------------------------

 /var/www/traction-service/releases/20221220144339/app/resources/v1/pacbio/container_material_resource.rb:52:in `rescue in state'
 /var/www/traction-service/releases/20221220144339/app/resources/v1/pacbio/container_material_resource.rb:52:in `state'
 /var/www/traction-service/shared/vendor/bundle/ruby/3.1.0/gems/jsonapi-resources-0.10.7/lib/jsonapi/resource_serializer.rb:227:in `public_send'
 /var/www/traction-service/shared/vendor/bundle/ruby/3.1.0/gems/jsonapi-resources-0.10.7/lib/jsonapi/resource_serializer.rb:227:in `block in attributes_hash'
 /home/ubuntu/.rbenv/versions/3.1.2/lib/ruby/3.1.0/set.rb:511:in `each_key'
 /home/ubuntu/.rbenv/versions/3.1.2/lib/ruby/3.1.0/set.rb:511:in `each'
 /var/www/traction-service/shared/vendor/bundle/ruby/3.1.0/gems/jsonapi-resources-0.10.7/lib/jsonapi/resource_serializer.rb:224:in `each_with_object'
 /var/www/traction-service/shared/vendor/bundle/ruby/3.1.0/gems/jsonapi-resources-0.10.7/lib/jsonapi/resource_serializer.rb:224:in `attributes_hash'
 /var/www/traction-service/shared/vendor/bundle/ruby/3.1.0/gems/jsonapi-resources-0.10.7/lib/jsonapi/resource_serializer.rb:177:in `object_hash'
 /var/www/traction-service/shared/vendor/bundle/ruby/3.1.0/gems/jsonapi-resources-0.10.7/lib/jsonapi/resource_serializer.rb:76:in `block (2 levels) in serialize_resource_set_to_hash_plural'
 /var/www/traction-service/shared/vendor/bundle/ruby/3.1.0/gems/jsonapi-resources-0.10.7/lib/jsonapi/resource_serializer.rb:75:in `each_value'
 /var/www/traction-service/shared/vendor/bundle/ruby/3.1.0/gems/jsonapi-resources-0.10.7/lib/jsonapi/resource_serializer.rb:75:in `block in serialize_resource_set_to_hash_plural'
 /var/www/traction-service/shared/vendor/bundle/ruby/3.1.0/gems/jsonapi-resources-0.10.7/lib/jsonapi/resource_serializer.rb:74:in `each_value'
 /var/www/traction-service/shared/vendor/bundle/ruby/3.1.0/gems/jsonapi-resources-0.10.7/lib/jsonapi/resource_serializer.rb:74:in `serialize_resource_set_to_hash_plural'
 /var/www/traction-service/shared/vendor/bundle/ruby/3.1.0/gems/jsonapi-resources-0.10.7/lib/jsonapi/operation_result.rb:74:in `to_hash'
 /var/www/traction-service/shared/vendor/bundle/ruby/3.1.0/gems/jsonapi-resources-0.10.7/lib/jsonapi/response_document.rb:33:in `add_result'
 /var/www/traction-service/shared/vendor/bundle/ruby/3.1.0/gems/jsonapi-resources-0.10.7/lib/jsonapi/acts_as_resource_controller.rb:141:in `process_operation'
 /var/www/traction-service/shared/vendor/bundle/ruby/3.1.0/gems/jsonapi-resources-0.10.7/lib/jsonapi/acts_as_resource_controller.rb:110:in `block (3 levels) in process_request'
 /var/www/traction-service/shared/vendor/bundle/ruby/3.1.0/gems/jsonapi-resources-0.10.7/lib/jsonapi/request_parser.rb:32:in `each'
 /var/www/traction-service/shared/vendor/bundle/ruby/3.1.0/gems/jsonapi-resources-0.10.7/lib/jsonapi/acts_as_resource_controller.rb:97:in `block (2 levels) in process_request'
 /var/www/traction-service/shared/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.4/lib/active_support/callbacks.rb:99:in `run_callbacks'
 /var/www/traction-service/shared/vendor/bundle/ruby/3.1.0/gems/jsonapi-resources-0.10.7/lib/jsonapi/acts_as_resource_controller.rb:96:in `block in process_request'
 /var/www/traction-service/shared/vendor/bundle/ruby/3.1.0/gems/jsonapi-resources-0.10.7/lib/jsonapi/acts_as_resource_controller.rb:132:in `process_operations'
 /var/www/traction-service/shared/vendor/bundle/ruby/3.1.0/gems/jsonapi-resources-0.10.7/lib/jsonapi/acts_as_resource_controller.rb:95:in `process_request'
 /var/www/traction-service/shared/vendor/bundle/ruby/3.1.0/gems/jsonapi-resources-0.10.7/lib/jsonapi/acts_as_resource_controller.rb:19:in `index'
 /var/www/traction-service/shared/vendor/bundle/ruby/3.1.0/gems/actionpack-7.0.4/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
 /var/www/traction-service/shared/vendor/bundle/ruby/3.1.0/gems/actionpack-7.0.4/lib/abstract_controller/base.rb:215:in `process_action'
 /var/www/traction-service/shared/vendor/bundle/ruby/3.1.0/gems/actionpack-7.0.4/lib/action_controller/metal/rendering.rb:53:in `process_action'
 /var/www/traction-service/shared/vendor/bundle/ruby/3.1.0/gems/actionpack-7.0.4/lib/abstract_controller/callbacks.rb:234:in `block in process_action'
 /var/www/traction-service/shared/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.4/lib/active_support/callbacks.rb:107:in `run_callbacks'
 /var/www/traction-service/shared/vendor/bundle/ruby/3.1.0/gems/actionpack-7.0.4/lib/abstract_controller/callbacks.rb:233:in `process_action'
 /var/www/traction-service/shared/vendor/bundle/ruby/3.1.0/gems/actionpack-7.0.4/lib/action_controller/metal/rescue.rb:22:in `process_action'
 /var/www/traction-service/shared/vendor/bundle/ruby/3.1.0/gems/actionpack-7.0.4/lib/action_controller/metal/instrumentation.rb:67:in `block in process_action'
 /var/www/traction-service/shared/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.4/lib/active_support/notifications.rb:206:in `block in instrument'
 /var/www/traction-service/shared/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.4/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
 /var/www/traction-service/shared/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.4/lib/active_support/notifications.rb:206:in `instrument'
 /var/www/traction-service/shared/vendor/bundle/ruby/3.1.0/gems/actionpack-7.0.4/lib/action_controller/metal/instrumentation.rb:66:in `process_action'
 /var/www/traction-service/shared/vendor/bundle/ruby/3.1.0/gems/actionpack-7.0.4/lib/action_controller/metal/params_wrapper.rb:259:in `process_action'
 /var/www/traction-service/shared/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.4/lib/active_record/railties/controller_runtime.rb:27:in `process_action'
 /var/www/traction-service/shared/vendor/bundle/ruby/3.1.0/gems/actionpack-7.0.4/lib/abstract_controller/base.rb:151:in `process'
 /var/www/traction-service/shared/vendor/bundle/ruby/3.1.0/gems/actionview-7.0.4/lib/action_view/rendering.rb:39:in `process'
 /var/www/traction-service/shared/vendor/bundle/ruby/3.1.0/gems/actionpack-7.0.4/lib/action_controller/metal.rb:188:in `dispatch'
 /var/www/traction-service/shared/vendor/bundle/ruby/3.1.0/gems/actionpack-7.0.4/lib/action_controller/metal.rb:251:in `dispatch'
 /var/www/traction-service/shared/vendor/bundle/ruby/3.1.0/gems/actionpack-7.0.4/lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
 /var/www/traction-service/shared/vendor/bundle/ruby/3.1.0/gems/actionpack-7.0.4/lib/action_dispatch/routing/route_set.rb:32:in `serve'
 /var/www/traction-service/shared/vendor/bundle/ruby/3.1.0/gems/actionpack-7.0.4/lib/action_dispatch/journey/router.rb:50:in `block in serve'
 /var/www/traction-service/shared/vendor/bundle/ruby/3.1.0/gems/actionpack-7.0.4/lib/action_dispatch/journey/router.rb:32:in `each'
 /var/www/traction-service/shared/vendor/bundle/ruby/3.1.0/gems/actionpack-7.0.4/lib/action_dispatch/journey/router.rb:32:in `serve'
 /var/www/traction-service/shared/vendor/bundle/ruby/3.1.0/gems/actionpack-7.0.4/lib/action_dispatch/routing/route_set.rb:852:in `call'
 /var/www/traction-service/shared/vendor/bundle/ruby/3.1.0/gems/flipper-0.25.4/lib/flipper/middleware/memoizer.rb:72:in `memoized_call'
 /var/www/traction-service/shared/vendor/bundle/ruby/3.1.0/gems/flipper-0.25.4/lib/flipper/middleware/memoizer.rb:37:in `call'
 /var/www/traction-service/shared/vendor/bundle/ruby/3.1.0/gems/exception_notification-4.5.0/lib/exception_notification/rack.rb:49:in `call'
 /var/www/traction-service/shared/vendor/bundle/ruby/3.1.0/gems/rack-2.2.4/lib/rack/etag.rb:27:in `call'
 /var/www/traction-service/shared/vendor/bundle/ruby/3.1.0/gems/rack-2.2.4/lib/rack/conditional_get.rb:27:in `call'
 /var/www/traction-service/shared/vendor/bundle/ruby/3.1.0/gems/rack-2.2.4/lib/rack/head.rb:12:in `call'
 /var/www/traction-service/shared/vendor/bundle/ruby/3.1.0/gems/actionpack-7.0.4/lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
 /var/www/traction-service/shared/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.4/lib/active_support/callbacks.rb:99:in `run_callbacks'
 /var/www/traction-service/shared/vendor/bundle/ruby/3.1.0/gems/actionpack-7.0.4/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
 /var/www/traction-service/shared/vendor/bundle/ruby/3.1.0/gems/actionpack-7.0.4/lib/action_dispatch/middleware/debug_exceptions.rb:28:in `call'
 /var/www/traction-service/shared/vendor/bundle/ruby/3.1.0/gems/actionpack-7.0.4/lib/action_dispatch/middleware/show_exceptions.rb:26:in `call'
 /var/www/traction-service/shared/vendor/bundle/ruby/3.1.0/gems/railties-7.0.4/lib/rails/rack/logger.rb:40:in `call_app'
 /var/www/traction-service/shared/vendor/bundle/ruby/3.1.0/gems/railties-7.0.4/lib/rails/rack/logger.rb:27:in `call'
 /var/www/traction-service/shared/vendor/bundle/ruby/3.1.0/gems/actionpack-7.0.4/lib/action_dispatch/middleware/remote_ip.rb:93:in `call'
 /var/www/traction-service/shared/vendor/bundle/ruby/3.1.0/gems/actionpack-7.0.4/lib/action_dispatch/middleware/request_id.rb:26:in `call'
 /var/www/traction-service/shared/vendor/bundle/ruby/3.1.0/gems/rack-2.2.4/lib/rack/runtime.rb:22:in `call'
 /var/www/traction-service/shared/vendor/bundle/ruby/3.1.0/gems/actionpack-7.0.4/lib/action_dispatch/middleware/executor.rb:14:in `call'
 /var/www/traction-service/shared/vendor/bundle/ruby/3.1.0/gems/actionpack-7.0.4/lib/action_dispatch/middleware/static.rb:23:in `call'
 /var/www/traction-service/shared/vendor/bundle/ruby/3.1.0/gems/rack-2.2.4/lib/rack/sendfile.rb:110:in `call'
 /var/www/traction-service/shared/vendor/bundle/ruby/3.1.0/gems/actionpack-7.0.4/lib/action_dispatch/middleware/host_authorization.rb:131:in `call'
 /var/www/traction-service/shared/vendor/bundle/ruby/3.1.0/gems/rack-cors-1.1.1/lib/rack/cors.rb:100:in `call'
 /var/www/traction-service/shared/vendor/bundle/ruby/3.1.0/gems/rack-cors-1.1.1/lib/rack/cors.rb:100:in `call'
 /var/www/traction-service/shared/vendor/bundle/ruby/3.1.0/gems/railties-7.0.4/lib/rails/engine.rb:530:in `call'
 /var/www/traction-service/shared/vendor/bundle/ruby/3.1.0/gems/puma-6.0.0/lib/puma/configuration.rb:268:in `call'
 /var/www/traction-service/shared/vendor/bundle/ruby/3.1.0/gems/puma-6.0.0/lib/puma/request.rb:89:in `block in handle_request'
 /var/www/traction-service/shared/vendor/bundle/ruby/3.1.0/gems/puma-6.0.0/lib/puma/thread_pool.rb:343:in `with_force_shutdown'
 /var/www/traction-service/shared/vendor/bundle/ruby/3.1.0/gems/puma-6.0.0/lib/puma/request.rb:88:in `handle_request'
 /var/www/traction-service/shared/vendor/bundle/ruby/3.1.0/gems/puma-6.0.0/lib/puma/server.rb:430:in `process_client'
 /var/www/traction-service/shared/vendor/bundle/ruby/3.1.0/gems/puma-6.0.0/lib/puma/server.rb:233:in `block in run'
 /var/www/traction-service/shared/vendor/bundle/ruby/3.1.0/gems/puma-6.0.0/lib/puma/thread_pool.rb:150:in `block in spawn_thread'

-------------------------------
Data:
-------------------------------

 * data: {}
```
